@extends('admin.layout')

@section('title', 'Input Data Kotak Amal')

@section('content')
    <section class="p-3">
        <form action="{{ route('admin.kotak-amal.store') }}" method="POST" id="main-form">
            @csrf

            <div class="d-flex justify-content-between align-items-center mb-4">
                <div class="d-flex align-items-center gap-2">
                    <a href="{{ route('admin.kotak-amal.index') }}" class="btn btn-light btn-sm rounded-4">
                        <i class="fas fa-arrow-left"></i>
                    </a>
                    <h4 class="fw-semibold mb-0">Input Data Kotak Amal</h4>
                </div>
                <div class="d-flex gap-2">
                    <a href="{{ route('admin.kotak-amal.index') }}" class="btn btn-light border">Batal</a>
                    <button type="submit" class="btn btn-success fw-bold" id="btn-save" disabled>
                        <i class="fas fa-save me-1"></i> Simpan Data
                    </button>
                </div>
            </div>

            <div class="row">
                {{-- Left Column: Identity & Officers --}}
                <div class="col-lg-5">
                    {{-- Identity --}}
                    <div class="card bg-white border-0 rounded-3 p-4 mb-4 shadow-sm">
                        <h5 class="fw-bold mb-3">Identitas Kotak Amal</h5>
                        <div class="mb-3">
                            <label class="form-label fw-semibold">Nama / Lokasi Kotak</label>
                            <input type="text" name="box_name" class="form-control"
                                placeholder="Contoh: Kotak Jumat Depan" required>
                        </div>
                        <div class="mb-3">
                            <label class="form-label fw-semibold">Tanggal Pembukaan</label>
                            <input type="date" name="collection_date" class="form-control" value="{{ date('Y-m-d') }}"
                                required>
                        </div>
                    </div>

                    {{-- Officers --}}
                    <div class="card bg-white border-0 rounded-3 p-4 mb-4 shadow-sm">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h5 class="fw-bold mb-0">Petugas / Saksi</h5>
                            <button type="button" class="btn btn-sm btn-outline-primary" onclick="addOfficer()">
                                <i class="fas fa-plus"></i> Tambah
                            </button>
                        </div>

                        <div id="officers-container">
                            {{-- Officer Item Template --}}
                        </div>
                    </div>
                </div>

                {{-- Right Column: Money Counting --}}
                <div class="col-lg-7">
                    <div class="card bg-white border-0 rounded-3 p-4 mb-4 shadow-sm">
                        <h5 class="fw-bold mb-3">Perhitungan Uang</h5>

                        <div class="table-responsive">
                            <table class="table table-bordered align-middle">
                                <thead class="table-light text-center">
                                    <tr>
                                        <th>Pecahan</th>
                                        <th width="120">Jumlah (Lembar/Keping)</th>
                                        <th>Subtotal</th>
                                        <th width="80">Kunci</th>
                                    </tr>
                                </thead>
                                <tbody id="money-table-body">
                                    {{-- Rows generated by JS --}}
                                </tbody>
                                <tfoot class="table-light">
                                    <tr>
                                        <td colspan="2" class="text-end fw-bold">TOTAL</td>
                                        <td class="text-primary fs-5 fw-bold" id="grand-total">Rp 0</td>
                                        <td class="text-center">
                                            <button type="button" class="btn btn-sm btn-success fw-semibold"
                                                onclick="lockAllRows()" title="Kunci Semua">
                                                <i class="fas fa-lock me-1"></i> Semua
                                            </button>
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </section>

    @push('scripts')
        <script>
            const denominations = [
                100000, 50000, 20000, 10000, 5000, 2000, 1000, 500, 200, 100
            ];

            let officerCount = 0;

            function formatRupiah(number) {
                return new Intl.NumberFormat('id-ID', {
                    style: 'currency',
                    currency: 'IDR',
                    maximumFractionDigits: 0
                }).format(number);
            }

            // --- OFFICER LOGIC ---
            function addOfficer() {
                const container = document.getElementById('officers-container');
                const index = officerCount++;

                const html = `
            <div class="officer-item border rounded p-3 mb-3 bg-light position-relative" id="officer-${index}">
                <button type="button" class="btn-close position-absolute top-0 end-0 m-2" onclick="removeOfficer(${index})"></button>
                <div class="mb-2">
                    <label class="form-label small fw-bold">Nama Petugas</label>
                    <input type="text" name="officers[${index}][name]" class="form-control form-control-sm officer-input" required oninput="checkValidity()">
                </div>
                <div class="mb-2">
                    <label class="form-label small fw-bold">No. HP</label>
                    <input type="text" name="officers[${index}][phone]" class="form-control form-control-sm">
                </div>
                <div>
                    <label class="form-label small fw-bold">Tanda Tangan</label>
                    <div class="border rounded bg-white p-1" style="position: relative;">
                        <canvas id="sig-canvas-${index}" class="sig-canvas" width="350" height="100" style="cursor: crosshair; display: block; width: 100%;"></canvas>
                        <input type="hidden" name="officers[${index}][signature]" id="sig-data-${index}" class="officer-sig">
                    </div>
                    <div class="d-flex gap-2 mt-1">
                        <button type="button" class="btn btn-sm btn-outline-secondary" onclick="clearSignature(${index})">
                            <i class="fas fa-eraser me-1"></i> Hapus
                        </button>
                        <button type="button" class="btn btn-sm btn-outline-success" onclick="confirmSignature(${index})">
                            <i class="fas fa-check me-1"></i> Konfirmasi
                        </button>
                    </div>
                </div>
            </div>`;

                container.insertAdjacentHTML('beforeend', html);
                initSignatureCanvas(index);
                checkValidity();
            }

            // --- SIGNATURE CANVAS ---
            let sigContexts = {};
            let sigDrawing = {};

            function initSignatureCanvas(index) {
                const canvas = document.getElementById(`sig-canvas-${index}`);
                if (!canvas) return;

                const ctx = canvas.getContext('2d');
                ctx.strokeStyle = '#000';
                ctx.lineWidth = 2;
                ctx.lineCap = 'round';

                sigContexts[index] = ctx;
                sigDrawing[index] = false;

                canvas.addEventListener('mousedown', (e) => startDrawing(e, index));
                canvas.addEventListener('mousemove', (e) => draw(e, index));
                canvas.addEventListener('mouseup', () => stopDrawing(index));
                canvas.addEventListener('mouseout', () => stopDrawing(index));

                // Touch support
                canvas.addEventListener('touchstart', (e) => {
                    e.preventDefault();
                    startDrawing(e.touches[0], index);
                });
                canvas.addEventListener('touchmove', (e) => {
                    e.preventDefault();
                    draw(e.touches[0], index);
                });
                canvas.addEventListener('touchend', () => stopDrawing(index));
            }

            function startDrawing(e, index) {
                sigDrawing[index] = true;
                const canvas = document.getElementById(`sig-canvas-${index}`);
                const rect = canvas.getBoundingClientRect();
                const x = (e.clientX - rect.left) * (canvas.width / rect.width);
                const y = (e.clientY - rect.top) * (canvas.height / rect.height);
                sigContexts[index].beginPath();
                sigContexts[index].moveTo(x, y);
            }

            function draw(e, index) {
                if (!sigDrawing[index]) return;
                const canvas = document.getElementById(`sig-canvas-${index}`);
                const rect = canvas.getBoundingClientRect();
                const x = (e.clientX - rect.left) * (canvas.width / rect.width);
                const y = (e.clientY - rect.top) * (canvas.height / rect.height);
                sigContexts[index].lineTo(x, y);
                sigContexts[index].stroke();
            }

            function stopDrawing(index) {
                sigDrawing[index] = false;
            }

            function clearSignature(index) {
                const canvas = document.getElementById(`sig-canvas-${index}`);
                const ctx = sigContexts[index];
                ctx.clearRect(0, 0, canvas.width, canvas.height);
                document.getElementById(`sig-data-${index}`).value = '';
                checkValidity();
            }

            function confirmSignature(index) {
                const canvas = document.getElementById(`sig-canvas-${index}`);
                const dataUrl = canvas.toDataURL('image/png');
                document.getElementById(`sig-data-${index}`).value = dataUrl;
                checkValidity();
                alert('Tanda tangan dikonfirmasi!');
            }

            function removeOfficer(index) {
                document.getElementById(`officer-${index}`).remove();
                delete sigContexts[index];
                delete sigDrawing[index];
                checkValidity();
            }

            // --- MONEY LOGIC ---
            function initMoneyTable() {
                const tbody = document.getElementById('money-table-body');
                let html = '';

                denominations.forEach((denom, idx) => {
                    html += `
                <tr data-denom="${denom}">
                    <td class="fw-bold text-end">${formatRupiah(denom)}</td>
                    <td>
                        <input type="number" name="details[${idx}][quantity]" class="form-control text-center money-qty" 
                               min="0" value="0" oninput="calculateRow(${denom}, ${idx})">
                        <input type="hidden" name="details[${idx}][nominal]" value="${denom}">
                        <input type="hidden" name="details[${idx}][is_locked]" value="0" class="lock-status">
                    </td>
                    <td class="text-end fw-bold row-subtotal">Rp 0</td>
                    <td class="text-center">
                        <button type="button" class="btn btn-sm btn-outline-secondary btn-lock" onclick="toggleLock(this, ${idx})">
                            <i class="fas fa-lock-open"></i>
                        </button>
                    </td>
                </tr>`;
                });

                tbody.innerHTML = html;
            }

            function calculateRow(denom, idx) {
                const row = document.querySelector(`tr[data-denom="${denom}"]`);
                const qtyInput = row.querySelector('.money-qty');
                const subtotalEl = row.querySelector('.row-subtotal');

                let qty = parseInt(qtyInput.value) || 0;
                if (qty < 0) {
                    qty = 0;
                    qtyInput.value = 0;
                }
                const subtotal = qty * denom;

                subtotalEl.innerText = formatRupiah(subtotal);
                calculateGrandTotal();
            }

            function calculateGrandTotal() {
                let total = 0;
                document.querySelectorAll('tr[data-denom]').forEach(row => {
                    const denom = parseInt(row.dataset.denom);
                    const qty = parseInt(row.querySelector('.money-qty').value) || 0;
                    total += denom * qty;
                });
                document.getElementById('grand-total').innerText = formatRupiah(total);
            }

            function toggleLock(btn, idx) {
                const row = btn.closest('tr');
                const input = row.querySelector('.money-qty');
                const lockInput = row.querySelector('.lock-status');
                const icon = btn.querySelector('i');

                // Check readOnly instead of disabled because we use readOnly for the 'locked' state
                if (input.readOnly) {
                    // Unlock
                    input.readOnly = false;
                    lockInput.value = "0";
                    btn.classList.remove('btn-success');
                    btn.classList.add('btn-outline-secondary');
                    icon.classList.remove('fa-lock');
                    icon.classList.add('fa-lock-open');
                } else {
                    // Lock
                    input.readOnly = true;
                    lockInput.value = "1";
                    btn.classList.remove('btn-outline-secondary');
                    btn.classList.add('btn-success');
                    icon.classList.remove('fa-lock-open');
                    icon.classList.add('fa-lock');
                }
                checkValidity();
            }

            function lockAllRows() {
                document.querySelectorAll('tr[data-denom]').forEach(row => {
                    const input = row.querySelector('.money-qty');
                    const lockInput = row.querySelector('.lock-status');
                    const btn = row.querySelector('.btn-lock');
                    const icon = btn.querySelector('i');

                    // Only lock if not already locked
                    if (!input.readOnly) {
                        input.readOnly = true;
                        lockInput.value = "1";
                        btn.classList.remove('btn-outline-secondary');
                        btn.classList.add('btn-success');
                        icon.classList.remove('fa-lock-open');
                        icon.classList.add('fa-lock');
                    }
                });
                checkValidity();
            }

            function checkValidity() {
                const officerItems = document.querySelectorAll('.officer-item');
                const moneyRows = document.querySelectorAll('tr[data-denom]');
                let allOfficersValid = officerItems.length > 0;
                let allMoneyLocked = true;

                // Check officers - name and signature required
                officerItems.forEach(item => {
                    const nameInput = item.querySelector('input[name*="[name]"]');
                    const sigInput = item.querySelector('.officer-sig');

                    if (!nameInput.value.trim()) allOfficersValid = false;
                    if (!sigInput || !sigInput.value) allOfficersValid = false;
                });

                // Check money locks
                moneyRows.forEach(row => {
                    const isLocked = row.querySelector('.lock-status').value === "1";
                    if (!isLocked) allMoneyLocked = false;
                });

                const btnSave = document.getElementById('btn-save');
                if (allOfficersValid && allMoneyLocked) {
                    btnSave.disabled = false;
                } else {
                    btnSave.disabled = true;
                }
            }

            // Init
            initMoneyTable();
            addOfficer(); // Add one default officer
        </script>
    @endpush
@endsection
